#!/usr/bin/env bash

APP_NAME=`basename $(pwd)`

docker-sync start
docker-compose run --rm spring gem install rails
docker-compose run --rm spring rails new $APP_NAME "$@"
docker-compose run --rm spring sh -c 'cp -iR '$APP_NAME'/. . && rm -rf '$APP_NAME
